import { Inter  } from 'next/font/google';

import "./globals.css";
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

// Importing the font and configuring it
const zillaS = Inter ({
  subsets: ['cyrillic'],
  display: 'swap',
});

export const metadata = {
  title: "Ladakh e hatti",
  description: "Generated by create next app",
  icons:{
    icon:'./favicon.ico'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={zillaS.className}>
      <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
